name: Build MAUI Practice-8 (Android)

on:
  push:
    branches: 
    - '!main'
  pull_request:
    branches:  
    - '!main'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Install .NET MAUI
      run: dotnet workload install maui
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release -f net8.0-android
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.2.1-node20
      with: 
        path: |
          ./**/*.aab
          ./**/*.apk
        retention-days: 3
